#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
fix_net_gt.py -- Offline ground-truth rewriter for mis-targeted NET faults.

WHY
---
netem qdisc for net_delay / net_loss is physically attached to the *catalog-gw*
pod netns (verified 2026-07-13: Chaos Mesh containerRecords SELECTED ->
catalog-gw-5f6fdf7bb-frnzn; PodNetworkChaos exists only for catalog-gw;
`tc qdisc show` -> catalog-gw eth0 = netem delay, catalog eth0 = noqueue).
Some already-collected cases labelled the network leg's root as `catalog`.
This script rewrites those labels in-place on the NATIVE tree.

DESIGN
------
* Data-driven, NOT name-driven: it walks every groundtruth.json and matches on
  `component_ground_truth[i].fault_class == "network"` AND
  `target_component != <gw-service>`.  Cases nobody remembered are found too.
* Corroboration guard: each matched leg must ALSO carry
  `intensity.scope` starting with "catalog_gw_egress" (the injector's own record
  that the qdisc went on the gw).  A net leg that is mis-targeted but lacks that
  witness is REFUSED (not silently rewritten) unless --force.
* The correct gw *instance* is resolved per-case from that case's own data
  (sibling leg -> own telemetry), never from a global hardcode, unless
  --gw-instance is given.
* Both groundtruth.json AND metadata.json are patched: metadata embeds
  `faults[]`, `root_causes[]` and a full copy of `ground_truth`, so fixing only
  groundtruth.json would leave the case self-inconsistent (the packager reads
  metadata).
* Idempotent: once target_component == gw-service the predicate no longer fires.
* Writer is byte-format preserving (indent=2, ensure_ascii=False, no trailing
  newline, LF) -- verified round-trip identical, so diffs are minimal.

SAFETY
------
* ★ 2026-07-13:本脚本是【极少数被允许写 native 采集树的脚本之一】,故意【不】调
  dataset_registry.assert_not_native() —— 它的工作就是原地修 (native trees)  里的
  groundtruth.json(GT 修复),挡住它等于废掉它。合法 native 写入者共两个:
    - chaos_k8s_runner.py : 采集器,native 的生产者;
    - fix_net_gt.py(本文件): 带 --dry-run 默认 + --backup-dir 强制备份 + FORBIDDEN 路径护栏
                             的一次性 GT 原地修复。
  【其余所有脚本一律只读 native】,派生物走 dataset_registry.runtime_dir()。
  背景:2026-07-13 一次 `eval_k8s_supervised.py --help` 就把 usage 文本写进了 native
  (默认输出根 = native + finally 里无条件写盘)。护栏建了不接 = 没建。
* Default is --dry-run.  --apply requires --backup-dir.
* Refuses to operate on any path containing "k8s_pilot_delivery" (packaging
  output; regenerate it from the fixed native tree instead).
* Skips derived `mr2/` artifacts by default (regenerated by the packager).

USAGE
-----
  python fix_net_gt.py --dry-run
  python fix_net_gt.py --dry-run --tree single_dense --tree dual_dense
  python fix_net_gt.py --apply --tree single_dense --tree dual_dense \
      --backup-dir <scratch>/gt_backup_20260713
"""
from __future__ import annotations

import argparse
import difflib
import glob
import json
import os
import re
import shutil
import sys

DEFAULT_ROOT = r"${OUTPUT_ROOT:-${REPO_DIR}/output}/k8s_pilot"
GW_SERVICE = "catalog-gw"
SCOPE_WITNESS = "catalog_gw_egress"
POD_RE = re.compile(r"catalog-gw-[a-z0-9]+-[a-z0-9]{5}")
# Never touch a packaged/delivered/archived tree -- only the native collection tree.
# ★ 2026-07-13: 交付树迁到 (delivery) (冻结)、旧交付迁到 (archived) ,
#   原来单靠 "k8s_pilot_delivery" 这一个串的护栏就【失效】了(新路径里根本没这个词)。
#   改成按目录段匹配,迁移后仍然拦得住。
FORBIDDEN = ("k8s_pilot_delivery", "_delivery", "_archive", "_runtime")


def _forbidden_hit(path):
    """Return the first FORBIDDEN marker present as a path segment, else None.

    Segment-wise (not substring) so a legit dir merely *containing* the letters
    is not blocked, while (delivery) ... and (archived) ... are.
    """
    segs = set(path.split("/"))
    for f in FORBIDDEN:
        if f in segs:
            return f
    return None


# ---------------------------------------------------------------- io helpers
def jload(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def jdumps(obj):
    # verified byte-identical to how the runner wrote these files
    return json.dumps(obj, indent=2, ensure_ascii=False)


def read_text(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def norm(p):
    return p.replace(os.sep, "/")


class CaseError(Exception):
    pass


# ------------------------------------------------------- instance resolution
def resolve_gw_instance(case_dir, gt, md, gw_service, override):
    """Return (instance, provenance). Per-case, never a global guess."""
    if override:
        return override, "--gw-instance override"

    # 1) sibling leg in the SAME case already targeting the gw (e.g. dual05 F2)
    for c in gt.get("component_ground_truth", []) or []:
        if c.get("target_component") == gw_service and c.get("target_container"):
            return c["target_container"], "sibling leg %s in same case" % c.get("fault_instance_id")

    # 2) the case's own telemetry / metadata
    found = set()
    for pat in ("raw/metrics/*.jsonl", "raw/operations/*.json"):
        for f in glob.glob(os.path.join(case_dir, *pat.split("/"))):
            try:
                found.update(POD_RE.findall(read_text(f)))
            except Exception:
                pass
    if not found and md:
        found.update(POD_RE.findall(jdumps(md)))

    if len(found) == 1:
        return found.pop(), "case's own telemetry (unique match)"
    if len(found) > 1:
        raise CaseError(
            "ambiguous gw instance in case telemetry: %s -- pass --gw-instance"
            % sorted(found))
    raise CaseError("could not resolve the %s instance from this case; pass --gw-instance" % gw_service)


# --------------------------------------------------------------- gt patching
def locate_root_index(gt, leg_idx, old_comp, old_inst):
    """Index into the parallel root_cause_* arrays for this leg.

    The arrays are ordered parallel to component_ground_truth (F1,F2,...).
    Verified on dual14: root_cause_services[0]==F1.target, [1]==F2.target.
    We assert that before trusting it; positional (not value) lookup is required
    because after the dual05 fix both entries become "catalog-gw" (duplicates).
    """
    svcs = gt.get("root_cause_services") or []
    insts = gt.get("root_cause_instances") or []
    if leg_idx < len(svcs) and leg_idx < len(insts):
        if svcs[leg_idx] == old_comp and insts[leg_idx] == old_inst:
            return leg_idx
    # fall back to a unique value match; refuse if ambiguous
    cands = [i for i, (s, n) in enumerate(zip(svcs, insts))
             if s == old_comp and n == old_inst]
    if len(cands) == 1:
        return cands[0]
    raise CaseError(
        "cannot map leg #%d (%s/%s) onto root_cause_services=%s root_cause_instances=%s"
        % (leg_idx, old_comp, old_inst, svcs, insts))


def patch_leg_dict(d, gw_service, gw_inst, changes, where):
    if d.get("target_component") != gw_service:
        changes.append("%s.target_component: %r -> %r" % (where, d.get("target_component"), gw_service))
        d["target_component"] = gw_service
    if d.get("target_container") != gw_inst:
        changes.append("%s.target_container: %r -> %r" % (where, d.get("target_container"), gw_inst))
        d["target_container"] = gw_inst


def recompute_distinct(container, gt_like, changes, where):
    """Only fires if the key actually exists (it does not today -- future-proof)."""
    key = "n_distinct_root_services"
    if key in container:
        new = len(set(gt_like.get("root_cause_services") or []))
        if container[key] != new:
            changes.append("%s.%s: %r -> %r" % (where, key, container[key], new))
            container[key] = new


def patch_ground_truth_block(gt, legs, gw_service, gw_inst, add_catalog_affected, changes, prefix):
    """Patch a groundtruth-shaped dict (top-level gt, or metadata['ground_truth'])."""
    cgt = gt.get("component_ground_truth") or []
    for leg_idx, fid, old_comp, old_inst in legs:
        ridx = locate_root_index(gt, leg_idx, old_comp, old_inst)
        patch_leg_dict(cgt[leg_idx], gw_service, gw_inst, changes,
                       "%scomponent_ground_truth[%d](%s)" % (prefix, leg_idx, fid))
        svcs = gt["root_cause_services"]
        insts = gt["root_cause_instances"]
        if svcs[ridx] != gw_service:
            changes.append("%sroot_cause_services[%d]: %r -> %r" % (prefix, ridx, svcs[ridx], gw_service))
            svcs[ridx] = gw_service
        if insts[ridx] != gw_inst:
            changes.append("%sroot_cause_instances[%d]: %r -> %r" % (prefix, ridx, insts[ridx], gw_inst))
            insts[ridx] = gw_inst

    if add_catalog_affected:
        aff = gt.setdefault("affected_services", [])
        for old_comp in sorted({l[2] for l in legs}):
            if old_comp not in aff:
                aff.append(old_comp)
                changes.append("%saffected_services: += %r" % (prefix, old_comp))

    recompute_distinct(gt, gt, changes, prefix.rstrip("."))


def patch_metadata(md, legs, gw_service, gw_inst, add_catalog_affected, changes):
    by_fid = {fid for _, fid, _, _ in legs}

    for j, f in enumerate(md.get("faults") or []):
        if f.get("fault_instance_id") in by_fid:
            patch_leg_dict(f, gw_service, gw_inst, changes, "faults[%d](%s)" % (j, f.get("fault_instance_id")))
            inner = f.get("component_ground_truth")
            if isinstance(inner, dict):
                patch_leg_dict(inner, gw_service, gw_inst, changes,
                               "faults[%d].component_ground_truth" % j)

    for k, rc in enumerate(md.get("root_causes") or []):
        if rc.get("fault_instance_id") in by_fid:
            if rc.get("service") != gw_service:
                changes.append("root_causes[%d].service: %r -> %r" % (k, rc.get("service"), gw_service))
                rc["service"] = gw_service
            if rc.get("instance") != gw_inst:
                changes.append("root_causes[%d].instance: %r -> %r" % (k, rc.get("instance"), gw_inst))
                rc["instance"] = gw_inst

    inner_gt = md.get("ground_truth")
    if isinstance(inner_gt, dict) and inner_gt.get("component_ground_truth"):
        inner_legs = []
        for leg_idx, fid, old_comp, old_inst in legs:
            cgt = inner_gt["component_ground_truth"]
            hit = next(((i, c) for i, c in enumerate(cgt) if c.get("fault_instance_id") == fid), None)
            if hit is None:
                raise CaseError("metadata.ground_truth is missing leg %s" % fid)
            i, c = hit
            inner_legs.append((i, fid, c.get("target_component"), c.get("target_container")))
        patch_ground_truth_block(inner_gt, inner_legs, gw_service, gw_inst,
                                 add_catalog_affected, changes, "ground_truth.")

    recompute_distinct(md, inner_gt if isinstance(inner_gt, dict) else md, changes, "")


# ------------------------------------------------------------------- driver
def find_bad_legs(gt, gw_service):
    out = []
    for i, c in enumerate(gt.get("component_ground_truth") or []):
        if c.get("fault_class") != "network":
            continue
        if c.get("target_component") == gw_service:
            continue
        out.append((i, c.get("fault_instance_id"), c.get("target_component"), c.get("target_container")))
    return out


def udiff(before, after, path):
    return "".join(difflib.unified_diff(
        (before + "\n").splitlines(keepends=True),
        (after + "\n").splitlines(keepends=True),
        fromfile="a/" + path, tofile="b/" + path, n=3))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=DEFAULT_ROOT)
    ap.add_argument("--dry-run", action="store_true", default=True)
    ap.add_argument("--apply", action="store_true",
                    help="actually write (requires --backup-dir)")
    ap.add_argument("--backup-dir", default=None)
    ap.add_argument("--tree", action="append", default=None,
                    help="restrict to a top-level tree under --root (repeatable), e.g. --tree single_dense")
    ap.add_argument("--gw-service", default=GW_SERVICE)
    ap.add_argument("--gw-instance", default=None,
                    help="override the gw pod name (default: resolve per-case from the case's own data)")
    ap.add_argument("--add-catalog-affected", action="store_true",
                    help="also append the old target (catalog) to affected_services. "
                         "OFF by default -- see NOTE in the run summary.")
    ap.add_argument("--include-mr2", action="store_true",
                    help="also patch derived mr2/ artifacts (default: skip; regenerate via packager)")
    ap.add_argument("--force", action="store_true",
                    help="rewrite net legs even without the catalog_gw_egress scope witness")
    ap.add_argument("--no-diff", action="store_true")
    args = ap.parse_args(argv)

    apply = args.apply
    if apply and not args.backup_dir:
        ap.error("--apply requires --backup-dir")
    root = os.path.abspath(args.root)
    hit = _forbidden_hit(norm(root))
    if hit:
        ap.error("refusing to touch a packaged/delivered/archived tree (matched %r); "
                 "fix the native tree ((native trees) ) and repackage" % hit)

    files = sorted(glob.glob(os.path.join(root, "**", "groundtruth.json"), recursive=True))
    skipped_mr2 = 0
    hits, errors, refused = [], [], []

    for gt_path in files:
        p = norm(gt_path)
        if _forbidden_hit(p):
            continue
        if "/mr2/" in p and not args.include_mr2:
            skipped_mr2 += 1
            continue
        rel = norm(os.path.relpath(gt_path, root))
        tree = rel.split("/")[0]
        if args.tree and tree not in args.tree:
            continue

        try:
            gt = jload(gt_path)
        except Exception as exc:
            errors.append((rel, "unreadable groundtruth.json: %s" % exc))
            continue

        legs = find_bad_legs(gt, args.gw_service)
        if not legs:
            continue  # clean, or already fixed -> idempotent no-op

        case_dir = os.path.dirname(gt_path)
        cgt = gt.get("component_ground_truth") or []

        # corroboration guard
        bad_scope = [fid for i, fid, _, _ in legs
                     if not str(((cgt[i].get("intensity") or {}).get("scope")) or "").startswith(SCOPE_WITNESS)]
        if bad_scope and not args.force:
            refused.append((rel, "net leg(s) %s lack the %r scope witness; use --force to override"
                            % (bad_scope, SCOPE_WITNESS)))
            continue

        md_path = os.path.join(case_dir, "metadata.json")
        md = None
        if os.path.exists(md_path):
            try:
                md = jload(md_path)
            except Exception as exc:
                errors.append((rel, "unreadable metadata.json: %s" % exc))
                continue

        try:
            gw_inst, prov = resolve_gw_instance(case_dir, gt, md, args.gw_service, args.gw_instance)
        except CaseError as exc:
            errors.append((rel, str(exc)))
            continue

        edits = []
        gt_before = jdumps(gt)
        md_before = jdumps(md) if md is not None else None
        try:
            patch_ground_truth_block(gt, legs, args.gw_service, gw_inst,
                                     args.add_catalog_affected, edits, "")
            if md is not None:
                patch_metadata(md, legs, args.gw_service, gw_inst,
                               args.add_catalog_affected, edits)
        except CaseError as exc:
            errors.append((rel, str(exc)))
            continue

        gt_after = jdumps(gt)
        md_after = jdumps(md) if md is not None else None
        writes = []
        if gt_after != gt_before:
            writes.append((gt_path, gt_before, gt_after))
        if md_after is not None and md_after != md_before:
            writes.append((md_path, md_before, md_after))
        if not writes:
            continue

        hits.append(dict(rel=rel, tree=tree, case_dir=case_dir, sample=gt.get("sample_id"),
                         legs=legs, gw_inst=gw_inst, prov=prov, edits=edits, writes=writes,
                         roots=gt.get("root_cause_services"), md=md is not None))

    # ------------------------------------------------------------- reporting
    mode = "APPLY" if apply else "DRY-RUN"
    print("=" * 78)
    print("fix_net_gt.py [%s]  root=%s" % (mode, norm(root)))
    print("  predicate: component_ground_truth[].fault_class=='network' AND target_component!=%r" % args.gw_service)
    print("  witness  : intensity.scope startswith %r" % SCOPE_WITNESS)
    print("  scanned  : %d groundtruth.json   (skipped %d derived mr2/)" % (len(files), skipped_mr2))
    print("=" * 78)

    by_tree = {}
    for h in hits:
        by_tree.setdefault(h["tree"], []).append(h)

    for tree in sorted(by_tree):
        hs = by_tree[tree]
        print("\n[%s]  %d case(s)" % (tree, len(hs)))
        for h in hs:
            legs_s = ", ".join("%s(%s->%s)" % (fid, oc, args.gw_service) for _, fid, oc, _ in h["legs"])
            print("  * %-22s %s" % (h["sample"], legs_s))
            print("      gw instance : %s   [%s]" % (h["gw_inst"], h["prov"]))
            print("      root_cause_services -> %s" % (h["roots"],))
            print("      files       : groundtruth.json%s" % (" + metadata.json" if h["md"] else "  (NO metadata.json!)"))
            for e in h["edits"]:
                print("        - %s" % e)

    if refused:
        print("\n!! REFUSED (missing scope witness) -- %d" % len(refused))
        for rel, why in refused:
            print("   %s\n     %s" % (rel, why))
    if errors:
        print("\n!! ERRORS -- %d" % len(errors))
        for rel, why in errors:
            print("   %s\n     %s" % (rel, why))

    if hits and not args.no_diff:
        print("\n" + "=" * 78)
        print("UNIFIED DIFFS")
        print("=" * 78)
        for h in hits:
            for path, before, after in h["writes"]:
                print(udiff(before, after, norm(os.path.relpath(path, root))))

    nfiles = sum(len(h["writes"]) for h in hits)
    print("=" * 78)
    print("SUMMARY: %d case(s), %d file(s) to rewrite, %d refused, %d error(s)"
          % (len(hits), nfiles, len(refused), len(errors)))
    if not args.add_catalog_affected:
        print("NOTE: affected_services left UNCHANGED (--add-catalog-affected to override).")
        print("      Evidence: dual02 is the exact structural control (two net legs, both roots")
        print("      = catalog-gw) and its affected_services is ['pricing'] with NO catalog.")
        print("      catalog appears in affected_services only in dual13/14/16, whose OTHER leg")
        print("      targets catalog directly. Each of these cases also PASSES its own")
        print("      catalog_server_p95_flat gate (catalog server p95 + catalog_direct probe both")
        print("      flat) -> catalog shows zero degradation. Adding it would contradict the")
        print("      case's own telemetry and diverge from the 45 correct cases.")
    print("=" * 78)

    if errors:
        return 2
    if not apply:
        if hits:
            print("\nDRY-RUN: nothing written. Re-run with --apply --backup-dir <dir> to commit.")
        return 0

    # ----------------------------------------------------------------- apply
    bdir = os.path.abspath(args.backup_dir)
    os.makedirs(bdir, exist_ok=True)
    written = 0
    for h in hits:
        for path, before, after in h["writes"]:
            rel = os.path.relpath(path, root)
            dst = os.path.join(bdir, rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(path, dst)              # backup BEFORE mutating
            tmp = path + ".tmp"
            with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(after)
            os.replace(tmp, path)
            written += 1
    print("\nAPPLIED: %d file(s) rewritten. Backups -> %s" % (written, norm(bdir)))
    print("Re-run --dry-run to confirm idempotency (expect 0 cases).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
